server:
  port: 8082


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect



logging.level:
  com.example.springaopexample: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace